"""
Report Generator Module - PDF and HTML Export
Author: Mubashir Ahmad Ameer, Rustam Khan
"""

import io
import base64
from datetime import datetime
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.units import inch


class ReportGenerator:
    """Handles professional report generation in multiple formats"""
    
    @staticmethod
    def generate_html_report(content: str) -> str:
        """Generate professional HTML report"""
        timestamp = datetime.now()
        
        return f"""
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <title>MediExplain Pro - Clinical Report</title>
            <style>
                * {{ margin: 0; padding: 0; box-sizing: border-box; }}
                body {{
                    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
                    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                    padding: 40px;
                    line-height: 1.6;
                }}
                .report-container {{
                    max-width: 1000px;
                    margin: 0 auto;
                    background: #FFFFFF;
                    border-radius: 20px;
                    box-shadow: 0 30px 60px rgba(0,0,0,0.2);
                    overflow: hidden;
                    animation: fadeInUp 0.6s ease-out;
                }}
                @keyframes fadeInUp {{
                    from {{ opacity: 0; transform: translateY(30px); }}
                    to {{ opacity: 1; transform: translateY(0); }}
                }}
                .report-header {{
                    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                    padding: 40px;
                    text-align: center;
                    color: #FFFFFF;
                }}
                .report-header h1 {{
                    font-size: 32px;
                    font-weight: 700;
                    margin-bottom: 10px;
                }}
                .report-body {{
                    padding: 40px;
                    color: #1a1a2e;
                }}
                .report-body h1 {{ font-size: 22px; color: #667eea; margin: 20px 0 12px; }}
                .report-body h2 {{ font-size: 18px; color: #764ba2; margin: 16px 0 8px; }}
                .report-body ul, .report-body ol {{ margin: 12px 0; padding-left: 28px; }}
                .disclaimer {{
                    background: #fef9e6;
                    border-left: 4px solid #d4af37;
                    padding: 20px;
                    margin-top: 30px;
                    border-radius: 12px;
                }}
                .report-footer {{
                    background: #f8f9fa;
                    padding: 20px;
                    text-align: center;
                    font-size: 12px;
                    color: #666;
                }}
            </style>
        </head>
        <body>
            <div class="report-container">
                <div class="report-header">
                    <h1>MediExplain Pro</h1>
                    <p>Enterprise Medical Intelligence System</p>
                    <p style="font-size: 14px;">{timestamp.strftime('%B %d, %Y at %I:%M %p')}</p>
                </div>
                <div class="report-body">
                    {content.replace(chr(10), '<br>')}
                    <div class="disclaimer">
                        <strong>Medical Disclaimer</strong><br>
                        This report is generated by AI for educational purposes only.
                        Consult healthcare professionals for medical decisions.
                    </div>
                </div>
                <div class="report-footer">
                    MediExplain Pro | Powered by GroqCloud | UET Taxila
                </div>
            </div>
        </body>
        </html>
        """
    
    @staticmethod
    def generate_pdf_report(content: str) -> io.BytesIO:
        """Generate professional PDF report"""
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=letter, 
                                topMargin=0.75*inch, bottomMargin=0.75*inch,
                                leftMargin=0.75*inch, rightMargin=0.75*inch)
        styles = getSampleStyleSheet()
        
        title_style = ParagraphStyle('CustomTitle', parent=styles['Heading1'], 
                                      fontSize=24, textColor=colors.HexColor('#667eea'), 
                                      spaceAfter=20, alignment=1)
        body_style = ParagraphStyle('CustomBody', parent=styles['Normal'], 
                                    fontSize=10, leading=14)
        
        story = []
        story.append(Paragraph("MediExplain Pro", title_style))
        story.append(Spacer(1, 0.25*inch))
        
        for line in content.split('\n'):
            if line.strip():
                story.append(Paragraph(line, body_style))
            story.append(Spacer(1, 0.1*inch))
        
        doc.build(story)
        buffer.seek(0)
        return buffer
    
    @staticmethod
    def get_html_download_link(content: str, filename: str) -> str:
        """Generate HTML download link"""
        html_content = ReportGenerator.generate_html_report(content)
        b64 = base64.b64encode(html_content.encode()).decode()
        return f'data:text/html;base64,{b64}'